datasets:
  epic_kitchens:
    # data_dtmuir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    splits:
      all: 
        json_dir: /vast/irr2020/EKU/FINAL
      train:
        h5_file: /scratch/bs3639/EKOS_train.h5
      test: 
        h5_file: /scratch/bs3639/EKOS_val.h5
        include_video_ids: ../epic-kitchens-100-annotations/EPIC_test_video_ids.csv # XXX: fixme
      val:
        h5_file: /scratch/bs3639/EKOS_val.h5
        exclude_video_ids: ../epic-kitchens-100-annotations/EPIC_test_video_ids.csv
        downsample_count: 2000

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: ../../epic-kitchens-100-annotations/EPIC_100_train.csv
        val:
          storage: ../../epic-kitchens-100-annotations/EPIC_100_validation.csv
          # storage: ../../epic-kitchens-100-annotations/EPIC_100_train.csv  # overfit sniff
        test:
          storage: ../../epic-kitchens-100-annotations/EPIC_100_validation.csv
          # storage: ../../epic-kitchens-100-annotations/EPIC_100_train.csv
      images:
        storage: /rgb_frames
        train:
          storage: /rgb_frames
        val:
          storage: /rgb_frames
        test:
          storage: /rgb_frames
