datasets:
  s20bn:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]
    splits:
      all:
        filename_format: '{video_id}/frame_{i:010d}.png'
        json_dir: /scratch/work/ptg/Something_ek_labels
      # train: 
      #   h5_file: /scratch/bs3639/SSv2_train.h5
      val:
        downsample_count: 2000
      #   h5_file: /scratch/bs3639/SSv2_val.h5
      # test:
      #   h5_file: /scratch/bs3639/SSv2_val.h5
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /scratch/work/ptg/Something_ek_labels/s20bn_train.csv
        val:
          storage: /scratch/work/ptg/Something_ek_labels/s20bn_validation.csv
        test:
          storage: /scratch/work/ptg/Something_ek_labels/s20bn_validation.csv
      images:
        storage: /frames/images
        train:
          storage: /frames/images
        val:
          storage: /frames/images
        test:
          storage: /frames/images
